import tempita
import sys


def main():
    process('adjac.f95.in', 'adjac.f95')


def process(src, dst):
    with open(src, 'rb') as f:
        text = f.read()
        tmpl = tempita.Template(text)
        out = tmpl.substitute()

    with open(dst, 'wb') as f:
        f.write("!! NOTE: this file is autogenerated from {}: do not edit manually\n".format(src))
        f.write(out)

    sys.exit(0)


if __name__ == "__main__":
    main()
