"""
generate.py SRC DST
"""
import sys
import argparse
import tempita


def main():
    p = argparse.ArgumentParser(usage=__doc__.strip())
    p.add_argument('src')
    p.add_argument('dst')
    args = p.parse_args()

    process(args.src, args.dst)


def process(src, dst):
    with open(src, 'rb') as f:
        text = f.read()
        tmpl = tempita.Template(text)
        out = tmpl.substitute()

    with open(dst, 'wb') as f:
        if dst.endswith('.f95'):
            f.write("!! NOTE: this file is autogenerated from {}: do not edit manually\n".format(src))
        else:
            f.write("/* NOTE: this file is autogenerated from {}: do not edit manually */\n".format(src))
        f.write(out)

    sys.exit(0)


if __name__ == "__main__":
    main()
